### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Dancho-bg** [DuendeSoftware/Support#771]
**Which version of Duende IdentityServer are you using?**
We use Duende.IdentityServer 6.2.3
**Which version of .NET are you using?**
We use .net core 6.0
**Describe the bug**
Sometimes (not often) we get NullReferenceException in our integration automation tests and also our customers complains. The issue is when they call /.well-known/openid-configuarion

Here is the stack trace:

Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_RequestServices()
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 28
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)|url: http://testdomain/Identity/.well-known/openid-configuration|action:

**Comment by Dancho-bg** [comment]
We also have this too:

Duende.IdentityServer.Hosting.IdentityServerMiddleware|Unhandled exception: Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Scheme()
   at Duende.IdentityServer.Services.DefaultServerUrls.get_Origin() in /_/src/IdentityServer/Services/Default/DefaultServerUrls.cs:line 32
   at Duende.IdentityServer.Extensions.ServerUrlExtensions.GetUnicodeOrigin(IServerUrls urls) in /_/src/IdentityServer/Extensions/ServerUrlExtensions.cs:line 26
   at Duende.IdentityServer.Services.DefaultIssuerNameService.GetCurrentAsync() in /_/src/IdentityServer/Services/Default/DefaultIssuerNameService.cs:line 40
   at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IdentityServerOptions options, IEndpointRouter router, IUserSession userSession, IEventService events, IIssuerNameService issuerNameService, ISessionCoordinationService sessionCoordinationService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 121|url: |action:

**Comment by josephdecock** [comment]
This error is coming from code that is relying on the incoming http request, and trying to use the request's scheme (like "https") and host to determine the issuer name to use. Sometimes that code path is invoked when there is no http context available, causing this error. We solved several related bugs in the 6.3 release (see https://github.com/DuendeSoftware/IdentityServer/issues/874). 

As a quick work-around, you can set the IssuerUri in the options explicitly to the uri to your identity server - e.g., "https://identityserver.example.com". That should prevent the code path that tries to use the scheme and host to determine the issuer uri from running in the first place. 

Longer term, if and when you eventually upgrade to 6.3, I think our fixes in that release should resolve this issue. If not, please do let us know.

**Comment by Dancho-bg** [comment]
It seems that after upgrading to the latest Duende version the issue still exists.

Today 1 integration test failed with:

2023-07-25 08:47:44.5737|1|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_RequestServices()
   at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 28
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)|url: http://wf-taflab4.qa.dw/DocuWare/Identity/.well-known/openid-configuration/jwks|action: 
2023-07-25 08:48:18.8951|1|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Method()
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.ValidateMethod(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)|url: |action: 
2023-07-25 08:48:18.8951||ERROR|IdentityService.Presentation.Web.Multitenancy.TenantResolvingMiddleware|An error occurred while resolving tenant id! System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Path()
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at IdentityService.Presentation.Web.Multitenancy.TenantResolvingStrategy.ProcessInvalidTenantIdAsync(HttpContext context, RequestDelegate next) in /home/tfsbuild/AzureAgents/linux-agent1/_work/309/s/src/Service/Presentation/Web/Multitenancy/TenantResolvingStrategy.cs:line 128
   at IdentityService.Presentation.Web.Multitenancy.TenantResolvingStrategy.ProcessRequestAsync(HttpContext context, RequestDelegate next) in /home/tfsbuild/AzureAgents/linux-agent1/_work/309/s/src/Service/Presentation/Web/Multitenancy/TenantResolvingStrategy.cs:line 71
   at IdentityService.Presentation.Web.Multitenancy.TenantResolvingMiddleware.InvokeAsync(HttpContext context) in /home/tfsbuild/AzureAgents/linux-agent1/_work/309/s/src/Service/Presentation/Web/Multitenancy/TenantResolvingMiddleware.cs:line 43|url: |action: 
2023-07-25 08:48:18.9122|2|ERROR|Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer|Connection ID "17293822575008284673", Request ID "80006bd9-0001-f000-b63f-84710c7967bb": An unhandled exception was thrown by the application. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.set_Path(PathString value)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()|url: |action:

**Comment by josephdecock** [comment]
It may be that some of these issues aren't coming from IdentityServer code. The second stack trace looks like the null reference is actually in your `TenantResolvingStrategy` class.

That said, the first stack trace does look like it's coming from our middleware. How is it that the log message includes a url, and yet there was no http context? You said this is happening in an integration test, so I wonder if your test is using some kind of test pipeline or other form of mocking, so that in the context of the test, the http context can't be resolved? Do you ever get this from a real http request? And does setting the IssuerUri option prevent the issue from occurring?

**Comment by Dancho-bg** [comment]
We added null checks there and now we get 

2023-08-02 05:09:05.7071|1|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request. 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Method()
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.ValidateMethod(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)|url: http://domain.com/Identity/.well-known/openid-configuration/jwks|action:

**Comment by josephdecock** [comment]
Okay, if you set the `IssuerUri` option does the issue persist?

**Comment by Dancho-bg** [comment]
The problem is that we cannot set IssuerUri, because domains are different.

**Comment by josephdecock** [comment]
Okay, then back to more original question, which is, can you describe the environment where these errors are occurring? Is it in fact in a test? The errors look like there is no http context available. That could happen in a test where the pipeline/http request was being faked or mocked in some way.

**Comment by Dancho-bg** [comment]
The errors occurs in our integration tests and on production on azure as well as on onpremise client machines. In the integration tests we do not mock http requests.

Updating Duende to 6.3 decrease the errors except this one: 
2023-08-02 05:09:05.7071|1|ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Method()
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.ValidateMethod(HttpContext context)
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)|url: [http://domain.com/Identity/.well-known/openid-configuration/jwks|action](http://domain.com/Identity/.well-known/openid-configuration/jwks%7Caction):

But hide most of the actual errors with this:
System.NotSupportedException with outerMessage (in azure) System.AggregateException: An error occurred while writing to logger(s). (Serialization and deserialization of 'System.IntPtr' instances are not supported. Path: $.Exception.TargetSite.MethodHandle.Value.) (Serialization and deserialization of 'System.IntPtr' instances are not supported. Path: $.Exception.TargetSite.MethodHandle.Value.)

**Comment by josephdecock** [comment]
Do you have [event ](https://docs.duendesoftware.com/identityserver/v6/diagnostics/events/) enabled? And in particular, are you raising error events, with code similar to this:

```
        var identityServer = builder.Services.AddIdentityServer(options =>
            {
                options.Events.RaiseErrorEvents = true;
```

**Comment by Dancho-bg** [comment]
Yes, we have all these: 

 options.Events.RaiseErrorEvents = true;
options.Events.RaiseInformationEvents = true;
options.Events.RaiseFailureEvents = true;
options.Events.RaiseSuccessEvents = true;

**Comment by josephdecock** [comment]
Okay, I think your issue is probably the same as what we saw in https://github.com/DuendeSoftware/IdentityServer/issues/1362. I suspect that if you disable failure events, you might get a more informative error message in your regular logs. Can you do that, at least for a little while to try to find out where the exception is being thrown?

**Comment by josephdecock** [comment]
Any update here?

**Comment by Dancho-bg** [comment]
Yesterday we upgraded Duende to 6.2.4 and again we have this error that I thought was fixed: 
System.AggregateException: An error occurred while writing to logger(s). (Serialization and deserialization of 'System.IntPtr' instances are not supported. Path: $.Exception.TargetSite.MethodHandle.Value.) (Serialization and deserialization of 'System.IntPtr' instances are not supported. Path: $.Exception.TargetSite.MethodHandle.Value.)

System.NotSupportedException at Duende.IdentityServer.Events.Event.ToString

**Comment by josephdecock** [comment]
@Dancho-bg, I'm in the process of backporting the fix for that bug to 6.3 [here](https://github.com/DuendeSoftware/IdentityServer/pull/1422).

**Comment by josephdecock** [comment]
We released 6.3.5 today with a fix this issue. We found a way to avoid a breaking change to the model while also preventing this serialization failure.

**Comment by Dancho-bg** [comment]
Thank you very much. We anticipated this fix. We cannot turn the events off. Today we will upgade the nuget.

**Comment by AndersAbel** [comment]
@Dancho-bg did the fix work for you? Can we now close this issue?

**Comment by AndersAbel** [comment]
Looks like this is solved, closing. Please reopen if needed.
